In [9]:
import sympy as sp
import numpy as np

In [10]:
def array(j):
    dim = int(2*j + 1)
    A = np.zeros(dim, dtype=object)  
    for i in range(dim):
        A[i] = j - i  
    return A

j = sp.Rational(input("Enter value of j: "))  
A = array(j)  

$Total$ $Angular$ $Momentum$ $in$ $X$ ($Jx$)

In [11]:
def Jx(j, A):
    dim = len(A)  
    B = sp.zeros(dim, dim)  

    for i in range(dim):
        for k in range(dim):
            a, b = 0, 0  
            if A[i] == A[k] + 1:
                a = sp.sqrt((j - A[k]) * (j + A[k] + 1))
            if A[i] == A[k] - 1:
                b = sp.sqrt((j + A[k]) * (j - A[k] + 1))
            B[i, k] = (a + b) / 2  
    
    return B 

$Total$ $Angular$ $Momentum$ $in$ $Y$ ($Jy$)

In [12]:
def Jy(j, A):
    dim = len(A)  
    B = sp.zeros(dim, dim)  

    for i in range(dim):
        for k in range(dim):
            a, b = 0, 0  
            if A[i] == A[k] + 1:
                a = sp.sqrt((j - A[k]) * (j + A[k] + 1))
            if A[i] == A[k] - 1:
                b = sp.sqrt((j + A[k]) * (j - A[k] + 1))
            B[i, k] = ((a - b) / (2*(sp.I) )) 
    
    return B 

$Total$ $Angular$ $Momentum$ $in$ $Z$ ($Jz$)

In [13]:
def Jz(j, A):
    dim = len(A)  
    B = sp.zeros(dim, dim)  

    for i in range(dim):
        for k in range(dim):
            a, b = 0, 0  
            if A[i] == A[k]:
                B[i, k] = A[k]
    
    return B

$Print$ $Jx ,Jy ,Jz$

In [14]:
print("Jx_matrix =")
Jx_matrix = Jx(j, A) 
sp.pprint(Jx_matrix) 
print("\nJy_matrix =")
Jy_matrix = Jy(j, A) 
sp.pprint(Jy_matrix) 
print("\nJz_matrix =")
Jz_matrix = Jz(j, A)  
sp.pprint(Jz_matrix)

print("Jx = (hbar/(2*pi)) * Jx_matrix")
print("Jy = (hbar/(2*pi)) * Jy_matrix")
print("Jz = (hbar/(2*pi)) * Jz_matrix")

Jx_matrix =
⎡    √2    ⎤
⎢0   ──  0 ⎥
⎢    2     ⎥
⎢          ⎥
⎢√2      √2⎥
⎢──  0   ──⎥
⎢2       2 ⎥
⎢          ⎥
⎢    √2    ⎥
⎢0   ──  0 ⎥
⎣    2     ⎦

Jy_matrix =
⎡      -√2⋅ⅈ         ⎤
⎢ 0    ──────    0   ⎥
⎢        2           ⎥
⎢                    ⎥
⎢√2⋅ⅈ          -√2⋅ⅈ ⎥
⎢────    0     ──────⎥
⎢ 2              2   ⎥
⎢                    ⎥
⎢       √2⋅ⅈ         ⎥
⎢ 0     ────     0   ⎥
⎣        2           ⎦

Jz_matrix =
⎡1  0  0 ⎤
⎢        ⎥
⎢0  0  0 ⎥
⎢        ⎥
⎣0  0  -1⎦
Jx = (hbar/(2*pi)) * Jx_matrix
Jy = (hbar/(2*pi)) * Jy_matrix
Jz = (hbar/(2*pi)) * Jz_matrix


$print$ $J^2$

In [15]:
JJ_matrix = sp.zeros(2*j +1)
JJ_matrix = np.dot(Jx_matrix,Jx_matrix) + np.dot(Jy_matrix,Jy_matrix) + np.dot(Jz_matrix,Jz_matrix)
print("\nJJ_matrix =")
sp.pprint(JJ_matrix)

print("JJ = (hbar/(2*pi))^2 * JJ_matrix")


JJ_matrix =
[[2 0 0] 
 [0 2 0] 
 [0 0 2]]
JJ = (hbar/(2*pi))^2 * JJ_matrix
